libs:
	../makeobj stdio/print stdio/input stdio/i_print stdio/i_input stdio.jo
	../makeobj stdlib/sqrt stdlib/sqr stdlib/sin stdlib/cos stdlib.jo # stdlib/tg stdlib/ctg stdlib/abs stdlib/int stdlib/float stdlib.jo
